name: C/C++ CI
on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'true'
    - name: create_builddir
      run: mkdir -p build
    - name: cmake
      run: cmake .. -DCOVERAGE=YES
      working-directory: ./build
    - name: build
      run: cmake --build . --target tests
      working-directory: ./build
    - name: tests
      run: ./tests
      working-directory: ./build
      if: matrix.os == 'ubuntu-latest'
    - name: tests
      run: .\Debug\tests.exe
      working-directory: ./build
      if: matrix.os == 'windows-latest'
    - name: install lcov
      run: ".github/workflows/install_latest_lcov.sh"
      if: matrix.os == 'ubuntu-latest'
    - name: generate coverage report
      run: cmake --build . -j $(nproc) --target coverage_html
      working-directory: ./build
      if: matrix.os == 'ubuntu-latest'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        token: ${{ secrets.CODECOV }}
        file: ./build/coverage.info
        name: codecoverage
        fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'true'
    - name: install clang-tidy
      run: ./.github/workflows/install_clang.sh
    - name: install include-what-you-use
      run: ./.github/workflows/install_include-what-you-use.sh
    - name: generate compile_commands
      run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
    - name: clang-tidy
      run: ./tools/clang-tidy.sh
    - name: clang-format
      run: ./tools/clang-format.sh
    - name: include-what-you-use
      run: ./tools/iwyu.sh

